apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quarkus-component-e2e
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-component-e2e
    app.kubernetes.io/part-of: e2e-demo-application
  name: quarkus-component-e2e
  namespace: appstudio-e2e-test
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: quarkus-component-e2e
status:
  loadBalancer: {}
